In [1]:
import torch

/Users/pratikaher/DGL/graph-rec/venv/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [10]:
a = torch.tensor([[0.0247],
        [0.0276],
        [0.0244],
        [0.0248],
        [0.0244]])

In [11]:
a

tensor([[0.0247],
        [0.0276],
        [0.0244],
        [0.0248],
        [0.0244]])

In [39]:
b = torch.tensor(0)

In [38]:
len(b.size()) == 0

True

In [36]:
b = b.squeeze(dim=-1)

In [40]:
b

tensor(0)

In [46]:
scores = torch.hstack([a, b])

In [47]:
scores

tensor([0.3624, 0.3637, 0.3624, 0.3622, 0.3644, 0.3618, 0.3651, 0.3630, 0.3594,
        0.3561, 0.3628, 0.3629, 0.3577, 0.2875, 0.3563, 0.3777, 0.3635, 0.2957,
        0.3625, 0.3623, 0.3625, 0.3547, 0.3568, 0.3612, 0.3547, 0.3620, 0.3624,
        0.3570, 0.3645, 0.3651, 0.3651, 0.3643, 0.3620, 0.3581, 0.3626, 0.3624,
        0.3590, 0.3643, 0.3652, 0.3629, 0.3583, 0.3655])

In [41]:
a = torch.tensor([0.3624, 0.3637, 0.3624, 0.3622, 0.3644, 0.3618, 0.3651]) 

b = torch.tensor([0.3630, 0.3594, 0.3561, 0.3628, 0.3629, 0.3577, 0.2875, 0.3563, 0.3777,
        0.3635, 0.2957, 0.3625, 0.3623, 0.3625, 0.3547, 0.3568, 0.3612, 0.3547,
        0.3620, 0.3624, 0.3570, 0.3645, 0.3651, 0.3651, 0.3643, 0.3620, 0.3581,
        0.3626, 0.3624, 0.3590, 0.3643, 0.3652, 0.3629, 0.3583, 0.3655])

In [57]:
import torch
import torch.nn.functional as F

input = torch.randn(3, requires_grad=True)
target = torch.empty(3).random_(2)
loss = F.binary_cross_entropy_with_logits(input, target)
loss.backward()

In [51]:
input

tensor([ 1.2692, -0.8965, -0.8134], requires_grad=True)

In [52]:
target

tensor([0., 1., 1.])

In [53]:
loss

tensor(1.3120, grad_fn=<BinaryCrossEntropyWithLogitsBackward>)

In [54]:
all_scores = torch.empty(0)

In [58]:
all_scores = torch.hstack([all_scores, loss])

In [59]:
all_scores

tensor([1.3120, 0.7512], grad_fn=<CatBackward>)

In [67]:
a = torch.tensor([[0.3948, 0.3937, 0.3946, 0.3948, 0.3948],
        [0.3868, 0.3869, 0.3876, 0.3868, 0.3871],
        [0.3887, 0.3896, 0.3896, 0.3908, 0.3892],
        [0.3888, 0.3963, 0.3884, 0.3872, 0.3975],
        [0.3994, 0.3983, 0.3980, 0.3989, 0.3970],
        [0.3907, 0.3884, 0.3899, 0.3898, 0.3902],
        [0.3889, 0.3899, 0.3877, 0.3879, 0.3895],
        [0.3885, 0.3892, 0.3881, 0.3897, 0.3889]])

In [68]:
b = torch.tensor([[0.3943],
        [0.3865],
        [0.3883],
        [0.3879],
        [0.3977],
        [0.3902],
        [0.3879],
        [0.3885]])

In [71]:
scores = a-b

In [70]:
all_scores = torch.empty(0)


In [72]:
all_scores = torch.cat((all_scores, scores), 0)

In [74]:
torch.mean(all_scores)

tensor(0.0009)